# Apply various labels on PRs
name: pr-regression-labels
on:
  issues:
    types: [opened, edited]
jobs:
  add-regression-label:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    outputs:
        is_regression: ${{ steps.check_regression.outputs.is_regression }}    
    steps:
    - name: Show template body
      uses: actions/github-script@v7
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TEMPLATE_BODY: ${{ github.event.issue.body }}
      with:
        script: |
          const checkboxPattern = /- \[(x|X)\] Select this option if this issue appears to be a regression\./i;
          const template = `${process.env.TEMPLATE_BODY}`
          const match = checkboxPattern.exec(template);
          const result = match ? match[1].toLowerCase() === 'x' : false;
          console.log(`Is regression: ${result}`);
          core.setOutput('is_regression', result);
        result-encoding: string
    - name: Label regression issues
      if: ${{ steps.check_regression.outputs.result == 'true' }}
      run: |
        # Add a label to the issue if it's a regression
        echo "Adding 'regression' label to the issue..."
